#include "lrstar_basic_defs.h"
#include "Vba_LexerTables_typedef.h"
#include "Vba_Parser.h"

void Vba_init_actions(lrstar_parser *parser); /* User-supplied */
void Vba_term_actions(lrstar_parser *parser); /* User-supplied */
static init_func_t Vba_init_funcs_[2] = {
   Vba_init_actions,
   Vba_term_actions
};

int Vba_error(lrstar_parser *parser, int &t);
int Vba_lookup(lrstar_parser *parser, int &t);
// Terminal action function pointers ...
static tact_func_t Vba_tact_funcs_[2] = {
   Vba_error,
   Vba_lookup,
};

// Node action function pointers ...
static nact_func_t Vba_nact_funcs_[81] = {
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
};


lrstar_parser generated_parser(/* grammar      */   "Vba",
                               /* user data    */   NULL,
                               /* actions      */   true,
                               /* debug_parser */   false,
                               /* debug_trace  */   false,
                               /* expecting    */   true,
                               /* insensitive  */   false,
                               /* lookaheads   */   1,
                               /* make_ast     */   true,
                               /* nd_parsing   */   false,
                               /* nd_threads   */   0,
                               /* node_actions */   true,
                               /* reversable   */   false,
                               /* semantics    */   true,
                               /* stksize      */   100,
                               /* term_actions */   true,
                               /* init_func    */   &Vba_init_funcs_[0],
                               /* tact_func    */   &Vba_tact_funcs_[0],
                               /* nact_func    */   &Vba_nact_funcs_[0]);

#include "lrstar_main.cpp"
