
////////////////////////////////////////////////////////////////////////////////////////////////////
//
//    Vba_ParserTables.hpp (generated by LRSTAR 24.0.017)

      #include "lrstar_basic_defs.h"
      #include "lrstar_parser_tables.h"
      #include "Vba_ParserTables.h"
      #include "Vba_Actions.h"


#include "Vba_ParserTables_instantiate.h"
