// Generated by LRSTAR 24.0.017
// DO NOT EDIT.

#if !defined(__PL1__ParserTables_TYPEDEF)
#define __PL1__ParserTables_TYPEDEF

#include "lrstar_parser_tables.h"

extern const char *PL1_grm_head_symb[632];
extern const char *PL1_grm_tact_name[2];
extern const uint16 PL1_grm_head_numb[1272];
extern const uint16 PL1_grm_f_tail[1273];
extern const int16 PL1_grm_tail[2199];
extern const char *PL1_grm_term_symb[226];
extern const int8 PL1_grm_arga[226];
extern const uint8 PL1_grm_Bm[668];
extern const uint16 PL1_grm_Br[860];
extern const uint8 PL1_grm_Bc[226];
extern const uint8 PL1_grm_Bf[226];
extern const int16 PL1_grm_Tm[4576];
extern const uint16 PL1_grm_Tr[860];
extern const uint8 PL1_grm_Tc[226];
extern const int16 PL1_grm_Nm[9999];
extern const uint16 PL1_grm_Nr[860];
extern const uint8 PL1_grm_Nc[1272];
extern const uint16 PL1_grm_Rm[121];
extern const int16 PL1_grm_Rr[860];
extern const uint8 PL1_grm_Rc[226];
extern const int8 PL1_grm_PL[1272];
extern const int8 PL1_grm_tact_numb[226];


template<typename T_term_symb,
         typename T_head_symb,
         typename T_tact_name,
         typename T_node_name,
         typename T_head_numb,
         typename T_f_tail,
         typename T_tail,
         typename T_arga,
         typename T_argx,
         typename T_argy,
         typename T_Bm,
         typename T_Br,
         typename T_Bc,
         typename T_Bf,
         typename T_Tm,
         typename T_Tr,
         typename T_Tc,
         typename T_Nm,
         typename T_Nr,
         typename T_Nc,
         typename T_Rm,
         typename T_Rr,
         typename T_Rc,
         typename T_PL,
         typename T_nd_fterm,
         typename T_nd_term,
         typename T_nd_faction,
         typename T_nd_action,
         typename T_tact_numb,
         typename T_node_numb,
         typename T_nact_numb,
         typename T_reverse>
   class PL1_parser_tables_ : public lrstar_parser_tables<T_term_symb, T_head_symb, T_tact_name, T_node_name, T_head_numb, T_f_tail, T_tail, T_arga, T_argx, T_argy, T_Bm, T_Br, T_Bc, T_Bf, T_Tm, T_Tr, T_Tc, T_Nm, T_Nr, T_Nc, T_Rm, T_Rr, T_Rc, T_PL, T_nd_fterm, T_nd_term, T_nd_faction, T_nd_action, T_tact_numb, T_node_numb, T_nact_numb, T_reverse>   {

public:

      PL1_parser_tables_() : lrstar_parser_tables<T_term_symb, T_head_symb, T_tact_name, T_node_name, T_head_numb, T_f_tail, T_tail, T_arga, T_argx, T_argy, T_Bm, T_Br, T_Bc, T_Bf, T_Tm, T_Tr, T_Tc, T_Nm, T_Nr, T_Nc, T_Rm, T_Rr, T_Rc, T_PL, T_nd_fterm, T_nd_term, T_nd_faction, T_nd_action, T_tact_numb, T_node_numb, T_nact_numb, T_reverse>(226, 632, 1272, 860, 859, 2, 0, 0, 1, false, &PL1_grm_term_symb[0], &PL1_grm_head_symb[0], &PL1_grm_tact_name[0], 0, &PL1_grm_head_numb[0], &PL1_grm_f_tail[0], &PL1_grm_tail[0], &PL1_grm_arga[0], 0, 0, &PL1_grm_Bm[0], &PL1_grm_Br[0], &PL1_grm_Bc[0], &PL1_grm_Bf[0], &PL1_grm_Tm[0], &PL1_grm_Tr[0], &PL1_grm_Tc[0], &PL1_grm_Nm[0], &PL1_grm_Nr[0], &PL1_grm_Nc[0], &PL1_grm_Rm[0], &PL1_grm_Rr[0], &PL1_grm_Rc[0], &PL1_grm_PL[0], 0, 0, 0, 0, &PL1_grm_tact_numb[0], 0, 0, 0)
      {
      }
   };

typedef PL1_parser_tables_<const char * const, const char * const, const char * const, const char * const, uint16, uint16, int16, int8, int32, int32, uint8, uint16, uint8, uint8, int16, uint16, uint8, int16, uint16, uint8, uint16, int16, uint8, int8, int32, int32, int32, int32, int8, int32, int32, int32> PL1_parser_tables_t;


#endif
