
////////////////////////////////////////////////////////////////////////////////////////////////////
//
//    PL1_ParserTables.hpp (generated by LRSTAR 24.0.017)

      #include "lrstar_basic_defs.h"
      #include "lrstar_parser_tables.h"
      #include "PL1_ParserTables.h"
      #include "PL1_Actions.h"


#include "PL1_ParserTables_instantiate.h"
