
////////////////////////////////////////////////////////////////////////////////
//
//    PL1_ParserTables.h (generated by LRSTAR 24.0.017)

      #pragma once

      #include "lrstar_library_defs.h"


      class lrstar_parser_tables
      {
         friend class lrstar_parser;
         public:
         static const char *term_symb[   226]; // Terminal symbols of the grammar.
         static const char *head_symb[   632]; // Nonterminal symbols of the grammar.
         static const char *tact_name[     2]; // Terminal action names found in the grammar.
         static const uint16 head_numb[  1272]; // Head symbol number for a production.
         static const uint16 f_tail   [  1273]; // First tail in a production.
         static const int16  tail     [  2199]; // Tail symbol number.
         static const int8   arga     [   226]; // Arguments for terminal actions.

         private:
         static const uint8  Bm[   668]       ; // Boolean matrix.
         static const uint16 Br[   860]       ; // Boolean matrix row.
         static const uint8  Bc[   226]       ; // Boolean matrix column.
         static const uint8 Bf[   226]       ; // Boolean matrix filter/mask.
         static const int16  Tm[  2354]       ; // Terminal transition matrix.
         static const uint16 Tr[   860]       ; // Terminal transition matrix row.
         static const uint8  Tc[   226]       ; // Terminal transition matrix column.
         static const int16  Nm[ 12401]       ; // Nonterminal transition matrix.
         static const uint16 Nr[   860]       ; // Nonterminal transition matrix row.
         static const uint16 Nc[  1272]       ; // Nonterminal transition matrix column.
         static const uint16 Rm[   121]       ; // Reduction matrix.
         static const int16  Rr[   860]       ; // Reduction matrix row.
         static const uint8  Rc[   226]       ; // Reduction matrix column.
         static const int8   PL[  1272]       ; // Production length minus one.

         static const int8   tact_numb[   226]; // Terminal action numbers.

         static int    (*tact_func[    2])(void *parser, int &t); // Terminal action function pointers.
      };

//
////////////////////////////////////////////////////////////////////////////////

