
////////////////////////////////////////////////////////////////////////////////
//
//    Calc_LexerTables.h (generated by DFA 24.0.016)

      #pragma once

      #undef  DEBUG_LEXER


/*
      static const uchar  Tm[  1428]        ; // Terminal transition matrix.
      static const ushort Tr[    55]        ; // Terminal transition matrix row.
      static const uchar  Tc[   256]        ; // Terminal transition matrix column.
      static const char   term_numb[    55] ; // Terminal number.
*/

//
////////////////////////////////////////////////////////////////////////////////
