// Generated by DFA 24.0.016)
// DO NOT EDIT.

#if !defined(__Calc__LexerTables_TYPEDEF)
#define __Calc__LexerTables_TYPEDEF

#include "lrstar_lexer.h"
typedef templ_lrstar_lexer<char, uchar, ushort, uchar> lexer_t;

#endif
