
////////////////////////////////////////////////////////////////////////////////
//
//    C_LexerTables.h (generated by DFA 24.0.016)

      #pragma once

      #undef  DEBUG_LEXER


/*
      static const uint8  Tm_[ 10148]        ; // Terminal transition matrix.
      static const uint16 Tr_[   207]        ; // Terminal transition matrix row.
      static const uint8  Tc_[   256]        ; // Terminal transition matrix column.
      static const int8   term_numb_[   207] ; // Terminal number.
*/

//
////////////////////////////////////////////////////////////////////////////////
