
////////////////////////////////////////////////////////////////////////////////////////////////////
//
//    C_ParserTables.hpp (generated by LRSTAR 24.0.017)

      #include "lrstar_basic_defs.h"
      #include "lrstar_parser_tables.h"
      #include "C_ParserTables.h"
      #include "C_Actions.h"


#include "C_ParserTables_instantiate.h"
