// Generated by LRSTAR 24.0.017
// DO NOT EDIT.

#if !defined(__PLSQL_Parser_H)
#define __PLSQL_Parser_H

#include "lrstar_basic_defs.h"
#include "lrstar_lexer.h"

#include "PLSQL_ParserTables_typedef.h"
#include "lrstar_parser.h"

#endif
