// Generated by DFA 24.0.016
// DO NOT EDIT.

#if !defined(__PLSQL__LexerTables_TYPEDEF)
#define __PLSQL__LexerTables_TYPEDEF

#include "lrstar_lexer.h"

extern const int16 PLSQL_lgr_term_numb[13027];
extern const uint16 PLSQL_lgr_Tm[933685];
extern const uint32 PLSQL_lgr_Tr[13027];
extern const uint8 PLSQL_lgr_Tc[256];

template<bool C_debug, typename T_term_numb, typename T_Tm, typename T_Tr, typename T_Tc>
class PLSQL_lexer_ : public lrstar_lexer<C_debug, T_term_numb, T_Tm, T_Tr, T_Tc> {
public:
    PLSQL_lexer_(char *input_start) :
      lrstar_lexer<C_debug, T_term_numb, T_Tm, T_Tr, T_Tc>(&PLSQL_lgr_term_numb[0], &PLSQL_lgr_Tm[0], &PLSQL_lgr_Tr[0], &PLSQL_lgr_Tc[0], input_start)
    {

    }


};


typedef PLSQL_lexer_<false, int16, uint16, uint32, uint8> PLSQL_lexer_t;

#endif
