
////////////////////////////////////////////////////////////////////////////////
//
//    PLSQL_LexerTables.h (generated by DFA 24.0.016)

      #pragma once

      #undef  DEBUG_LEXER


/*
      static const ushort Tm[1071672]        ; // Terminal transition matrix.
      static const uint   Tr[ 13027]        ; // Terminal transition matrix row.
      static const uchar  Tc[   256]        ; // Terminal transition matrix column.
      static const short  term_numb[ 13027] ; // Terminal number.
*/

//
////////////////////////////////////////////////////////////////////////////////
