
////////////////////////////////////////////////////////////////////////////////
//
//    PLSQL_LexerTables.h (generated by DFA 24.0.016)

      #pragma once

      #undef  DEBUG_LEXER


/*
      static const uint16 Tm_[1071672]        ; // Terminal transition matrix.
      static const uint32 Tr_[ 13027]        ; // Terminal transition matrix row.
      static const uint8  Tc_[   256]        ; // Terminal transition matrix column.
      static const int16  term_numb_[ 13027] ; // Terminal number.
*/

//
////////////////////////////////////////////////////////////////////////////////
