// Generated by LRSTAR 24.0.017
// DO NOT EDIT.

#if !defined(__C11__ParserTables_TYPEDEF)
#define __C11__ParserTables_TYPEDEF

#include "lrstar_parser_tables.h"
typedef templ_lrstar_parser_tables<const char * const, const char * const, const char * const, const char * const, uint8, uint16, int8, int8, uint32, uint32, uint8, uint16, uint8, uint8, int16, uint16, uint8, int16, uint16, uint8, uint8, uint8, uint8, uint8, uint32, uint32, uint32, uint32, int8, uint32, uint32, uint32> C11_parser_tables_t;

typedef C11_parser_tables_t parser_tables_t;

#endif
