// Generated by DFA 24.0.016
// DO NOT EDIT.

#if !defined(__LRK__LexerTables_TYPEDEF)
#define __LRK__LexerTables_TYPEDEF

#include "lrstar_lexer.h"
typedef templ_lrstar_lexer<int8, uint8, uint16, uint8> lexer_t;

#endif
