/* This file is generated by lrstar and will be overwritten by it. */

#include "lrstar_basic_defs.h"
#include "delphi_LexerTables_typedef.h"
#include "delphi_Parser.h"
#include "delphi_user.h"
#include "delphi_user_init_actions.h"
#include "delphi_user_term_actions.h"
#include "delphi_user_error.h"
#include "delphi_user_lookup.h"
