/* This file is generated by lrstar and will be overwritten by it. */

#include "lrstar_basic_defs.h"
#include "ALGOL60_LexerTables_typedef.h"
#include "ALGOL60_Parser.h"
#include "ALGOL60_user.h"
#include "ALGOL60_user_init_actions.h"
#include "ALGOL60_user_term_actions.h"
#include "ALGOL60_user_error.h"
#include "ALGOL60_user_lookup.h"
