
////////////////////////////////////////////////////////////////////////////////
//
//    Ada_ParserTables.h (generated by LRSTAR 24.0.017)

      #pragma once

      #undef  GRAMMAR
      #undef  PARSER
      #undef  PARSER_TABLES
      #undef  LEXER
      #undef  ACTIONS
      #undef  TERM_ACTIONS
      #undef  NODE_ACTIONS
      #undef  INSENSITIVE
      #undef  LOOKAHEADS
      #undef  DEBUG_PARSER
      #undef  DEBUG_TRACE
      #undef  MAKE_AST
      #undef  EXPECTING
      #undef  REVERSABLE
      #undef  SEMANTICS
      #undef  ND_PARSING
      #undef  ND_THREADS

      #define GRAMMAR      "Ada"
      #define PARSER        Ada_Parser
      #define PARSER_TABLES Ada_ParserTables
      #define LEXER         Ada_Lexer
      #define ACTIONS       Ada_Actions
      #define TERM_ACTIONS  Ada_TermActions
      #define LOOKAHEADS    1
      #define EXPECTING


      #define TOP_DOWN  0
      #define PASS_OVER 1
      #define BOTTOM_UP 2

      class Ada_ParserTables
      {
         friend class Ada_Parser;
         public:
         static const char *term_symb[    93]; // Terminal symbols of the grammar.
         static const char *head_symb[   205]; // Nonterminal symbols of the grammar.
         static const char *tact_name[     2]; // Terminal action names found in the grammar.
         static const uchar  head_numb[   414]; // Head symbol number for a production.
         static const ushort f_tail   [   415]; // First tail in a production.
         static const short  tail     [   903]; // Tail symbol number.
         static const char   arga     [    93]; // Arguments for terminal actions.

         private:
         static const uchar  Bm[   805]       ; // Boolean matrix.
         static const ushort Br[   464]       ; // Boolean matrix row.
         static const uchar  Bc[    93]       ; // Boolean matrix column.
         static const uchar Bf[    93]       ; // Boolean matrix filter/mask.
         static const short  Tm[   861]       ; // Terminal transition matrix.
         static const ushort Tr[   464]       ; // Terminal transition matrix row.
         static const uchar  Tc[    93]       ; // Terminal transition matrix column.
         static const short  Nm[  4736]       ; // Nonterminal transition matrix.
         static const ushort Nr[   464]       ; // Nonterminal transition matrix row.
         static const uchar  Nc[   414]       ; // Nonterminal transition matrix column.
         static const ushort Rm[   374]       ; // Reduction matrix.
         static const short  Rr[   464]       ; // Reduction matrix row.
         static const uchar  Rc[    93]       ; // Reduction matrix column.
         static const char   PL[   414]       ; // Production length minus one.

         static const char   tact_numb[    93]; // Terminal action numbers.

         static void   (*init_func[    2]) ()       ; // Init action function pointers.
         static int    (*tact_func[    2]) (int& t) ; // Terminal action function pointers.
      };

//
////////////////////////////////////////////////////////////////////////////////

