/* This file is generated by lrstar and will be overwritten by it. */

#include "lrstar_basic_defs.h"
#include "Ada_LexerTables_typedef.h"
#include "Ada_Parser.h"
#include "Ada_user.h"
#include "Ada_user_init_actions.h"
#include "Ada_user_term_actions.h"
#include "Ada_user_error.h"
#include "Ada_user_lookup.h"
