
////////////////////////////////////////////////////////////////////////////////
//
//    ANTLR_LexerTables.h (generated by DFA 24.0.016)

      #pragma once

      #undef  LEXER
      #undef  DEBUG_LEXER

      #define LEXER         ANTLR_Lexer

/*
      static uchar  Tm[  6441]        ; // Terminal transition matrix.
      static ushort Tr[   136]        ; // Terminal transition matrix row.
      static uchar  Tc[   256]        ; // Terminal transition matrix column.
      static char   term_numb[   136] ; // Terminal number.
*/

//
////////////////////////////////////////////////////////////////////////////////
