
////////////////////////////////////////////////////////////////////////////////
//
//    ANTLR_LexerTables.h (generated by DFA 24.0.016)

      #pragma once

      #undef  DEBUG_LEXER


/*
      static const uchar  Tm_[  6441]        ; // Terminal transition matrix.
      static const ushort Tr_[   136]        ; // Terminal transition matrix row.
      static const uchar  Tc_[   256]        ; // Terminal transition matrix column.
      static const char   term_numb_[   136] ; // Terminal number.
*/

//
////////////////////////////////////////////////////////////////////////////////
