
////////////////////////////////////////////////////////////////////////////////////////////////////
//
//    ANTLR_ParserTables.hpp (generated by LRSTAR 24.0.017)

      #include "lrstar_basic_defs.h"
      #include "lrstar_parser_tables.h"
      #include "ANTLR_ParserTables.h"
      #include "ANTLR_Actions.h"


#include "ANTLR_ParserTables_instantiate.h"
