// Generated by DFA 24.0.016
// DO NOT EDIT.

#if !defined(__ANTLR__LexerTables_TYPEDEF)
#define __ANTLR__LexerTables_TYPEDEF

#include "lrstar_lexer.h"
typedef templ_lrstar_lexer<false, int8, uint8, uint16, uint8> ANTLR_lexer_t;

#endif
