
////////////////////////////////////////////////////////////////////////////////
//
//    Modula2_LexerTables.h (generated by DFA 24.0.016)

      #pragma once

      #undef  LEXER
      #undef  DEBUG_LEXER

      #define LEXER         Modula2_Lexer

/*
      static uchar  Tm[ 10530]        ; // Terminal transition matrix.
      static ushort Tr[   218]        ; // Terminal transition matrix row.
      static uchar  Tc[   256]        ; // Terminal transition matrix column.
      static char   term_numb[   218] ; // Terminal number.
*/

//
////////////////////////////////////////////////////////////////////////////////
