// Generated by LRSTAR 24.0.017
// DO NOT EDIT.

#if !defined(__Java9_Parser_H)
#define __Java9_Parser_H

#include "lrstar_basic_defs.h"
#include "lrstar_lexer.h"

enum nodecon {
   N_start = 0,
};

#include "Java9_ParserTables_typedef.h"
#include "lrstar_parser.h"

extern const char Java9_grammar_name[];

typedef lrstar_parser</* grammar           */   Java9_grammar_name,
                      /* actions           */   true,
                      /* debug_parser      */   false,
                      /* debug_trace       */   false,
                      /* expecting         */   true,
                      /* insensitive       */   false,
                      /* lookaheads        */   30,
                      /* make_ast          */   true,
                      /* nd_parsing        */   true,
                      /* nd_threads        */   5,
                      /* node_actions      */   true,
                      /* reversable        */   false,
                      /* semantics         */   false,
                      /* stksize           */   100,
                      /* term_actions      */   true,
                      /* lexer table type  */   Java9_lexer_t,
                      /* parser table type */   Java9_parser_tables_t> Java9_parser_t;

#endif
