/* This file is generated by lrstar and will be overwritten by it. */

#include "lrstar_basic_defs.h"
#include "Java9_LexerTables_typedef.h"
#include "Java9_Parser.h"
#include "Java9_user.h"
#include "Java9_user_init_actions.h"
#include "Java9_user_term_actions.h"
#include "Java9_user_error.h"
#include "Java9_user_lookup.h"
