
////////////////////////////////////////////////////////////////////////////////
//
//    Java9_LexerTables.h (generated by DFA 24.0.016)

      #pragma once

      #undef  LEXER
      #undef  DEBUG_LEXER

      #define LEXER         Java9_Lexer

/*
      static ushort Tm[ 27393]        ; // Terminal transition matrix.
      static ushort Tr[   433]        ; // Terminal transition matrix row.
      static uchar  Tc[   256]        ; // Terminal transition matrix column.
      static char   term_numb[   433] ; // Terminal number.
*/

//
////////////////////////////////////////////////////////////////////////////////
