
////////////////////////////////////////////////////////////////////////////////
//
//    Java9_LexerTables.h (generated by DFA 24.0.016)

      #pragma once

      #undef  DEBUG_LEXER


/*
      static const ushort Tm_[ 27393]        ; // Terminal transition matrix.
      static const ushort Tr_[   433]        ; // Terminal transition matrix row.
      static const uchar  Tc_[   256]        ; // Terminal transition matrix column.
      static const char   term_numb_[   433] ; // Terminal number.
*/

//
////////////////////////////////////////////////////////////////////////////////
