
////////////////////////////////////////////////////////////////////////////////
//
//    Pascal_LexerTables.h (generated by DFA 24.0.016)

      #pragma once

      #undef  LEXER
      #undef  DEBUG_LEXER

      #define LEXER         Pascal_Lexer

/*
      static const ushort Tm[ 18592]        ; // Terminal transition matrix.
      static const ushort Tr[   353]        ; // Terminal transition matrix row.
      static const uchar  Tc[   256]        ; // Terminal transition matrix column.
      static const char   term_numb[   353] ; // Terminal number.
*/

//
////////////////////////////////////////////////////////////////////////////////
