
/* Lexical symbols found in Hello.grm.
   This file was generated by LRSTAR 24.0.017.
*/

   <eof>                              1
   <identifier>                       2

   'GREET'                            3

   '.'                                4

/* End of Hello lexical symbols. */

