// Generated by DFA 24.0.016
// DO NOT EDIT.

#if !defined(__Hello__LexerTables_TYPEDEF)
#define __Hello__LexerTables_TYPEDEF

#include "lrstar_lexer.h"

extern const int8 Hello_lgr_term_numb[11];
extern const uint8 Hello_lgr_Tm[90];
extern const uint8 Hello_lgr_Tr[11];
extern const uint8 Hello_lgr_Tc[256];

template<bool C_debug, typename T_term_numb, typename T_Tm, typename T_Tr, typename T_Tc>
class Hello_lexer_ : public lrstar_lexer<C_debug, T_term_numb, T_Tm, T_Tr, T_Tc> {
public:
    Hello_lexer_(char *input_start) :
      lrstar_lexer<C_debug, T_term_numb, T_Tm, T_Tr, T_Tc>(&Hello_lgr_term_numb[0], &Hello_lgr_Tm[0], &Hello_lgr_Tr[0], &Hello_lgr_Tc[0], input_start)
    {

    }


};


typedef Hello_lexer_<false, int8, uint8, uint8, uint8> Hello_lexer_t;

#endif
