
////////////////////////////////////////////////////////////////////////////////
//
//    CICS_ParserTables.h (generated by LRSTAR 24.0.017)

      #pragma once



      #define TOP_DOWN  0
      #define PASS_OVER 1
      #define BOTTOM_UP 2

      class CICS_ParserTables
      {
         friend class CICS_Parser;
         public:
         static const char *term_symb[   216]; // Terminal symbols of the grammar.
         static const char *head_symb[   369]; // Nonterminal symbols of the grammar.
         static const char *tact_name[     2]; // Terminal action names found in the grammar.
         static const ushort head_numb[   821]; // Head symbol number for a production.
         static const ushort f_tail   [   822]; // First tail in a production.
         static const short  tail     [  1488]; // Tail symbol number.
         static const char   arga     [   216]; // Arguments for terminal actions.

         private:
         static const uchar  Bm[   310]       ; // Boolean matrix.
         static const ushort Br[   668]       ; // Boolean matrix row.
         static const uchar  Bc[   216]       ; // Boolean matrix column.
         static const uchar Bf[   216]       ; // Boolean matrix filter/mask.
         static const short  Tm[  1304]       ; // Terminal transition matrix.
         static const ushort Tr[   668]       ; // Terminal transition matrix row.
         static const uchar  Tc[   216]       ; // Terminal transition matrix column.
         static const short  Nm[   733]       ; // Nonterminal transition matrix.
         static const ushort Nr[   668]       ; // Nonterminal transition matrix row.
         static const ushort Nc[   821]       ; // Nonterminal transition matrix column.
         static const uchar  Rm[     1]       ; // Reduction matrix.
         static const ushort Rr[   668]       ; // Reduction matrix row.
         static const uchar  Rc[   216]       ; // Reduction matrix column.
         static const char   PL[   821]       ; // Production length minus one.

         static const char   tact_numb[   216]; // Terminal action numbers.

         static void   (*init_func[    2]) ()       ; // Init action function pointers.
         static int    (*tact_func[    2]) (int& t) ; // Terminal action function pointers.
      };

//
////////////////////////////////////////////////////////////////////////////////

