// Generated by LRSTAR 24.0.017
// DO NOT EDIT.

#if !defined(__JSON__ParserTables_TYPEDEF)
#define __JSON__ParserTables_TYPEDEF

#include "lrstar_parser_tables.h"
typedef templ_lrstar_parser_tables<
   /* term_symb */  const char * const,
   /* head_symb */  const char * const,
   /* tact_name */  const char * const,
   /* node_name */  const char * const,
   /* head_numb */  uint8,
   /* f_tail */  uint8,
   /* tail */  int8,
   /* arga */  int8,
   /* argx */  int8,
   /* argy */  int32,
   /* Bm */  uint8,
   /* Br */  uint8,
   /* Bc */  uint8,
   /* Bf */  uint8,
   /* Tm */  int8,
   /* Tr */  uint8,
   /* Tc */  uint8,
   /* Nm */  int8,
   /* Nr */  uint8,
   /* Nc */  uint8,
   /* Rm */  uint8,
   /* Rr */  uint8,
   /* Rc */  uint8,
   /* PL */  uint8,
   /* nd_fterm */  int32,
   /* nd_term */  int32,
   /* nd_faction */  int32,
   /* nd_action */  int32,
   /* tact_numb */  int8,
   /* node_numb */  int8,
   /* nact_numb */  int8,
   /* reverse */ int32> JSON_parser_tables_t;


#endif
