
////////////////////////////////////////////////////////////////////////////////////////////////////
//
//    Dbase_ParserTables.hpp (generated by LRSTAR 24.0.017)

      #include "lrstar_basic_defs.h"
      #include "lrstar_parser_tables.h"
      #include "Dbase_ParserTables.h"
      #include "Dbase_Actions.h"


#include "Dbase_ParserTables_instantiate.h"
