// Generated by DFA 24.0.016
// DO NOT EDIT.

#if !defined(__Typedef__LexerTables_TYPEDEF)
#define __Typedef__LexerTables_TYPEDEF

#include "lrstar_lexer.h"

extern const int8 Typedef_lgr_term_numb[50];
extern const uint8 Typedef_lgr_Tm[1170];
extern const uint16 Typedef_lgr_Tr[50];
extern const uint8 Typedef_lgr_Tc[256];

template<bool C_debug, typename T_term_numb, typename T_Tm, typename T_Tr, typename T_Tc>
class Typedef_lexer_ : public lrstar_lexer<C_debug, T_term_numb, T_Tm, T_Tr, T_Tc> {
public:
    Typedef_lexer_(char *input_start) :
      lrstar_lexer<C_debug, T_term_numb, T_Tm, T_Tr, T_Tc>(&Typedef_lgr_term_numb[0], &Typedef_lgr_Tm[0], &Typedef_lgr_Tr[0], &Typedef_lgr_Tc[0], input_start)
    {

    }


};


typedef Typedef_lexer_<false, int8, uint8, uint16, uint8> Typedef_lexer_t;

#endif
