// Generated by LRSTAR 24.0.017
// DO NOT EDIT.

#if !defined(__Typedef_Parser_H)
#define __Typedef_Parser_H

#include "lrstar_basic_defs.h"
#include "lrstar_lexer.h"

enum nodecon {
   N_hello_ = 0,
};

#include "Typedef_ParserTables_typedef.h"
#include "lrstar_parser.h"

#endif
