#!/bin/bash
# Copyright (c) 2023 Logic Magicians Software
#
# Do not run.  Use 'source' to load into environment.
#
#
# BSD 3 License
#
SCRIPT="${BASH_SOURCE[0]}"
SRC_DIR=$(dirname "${SCRIPT}");
source $(readlink -f "${SRC_DIR}/functions");


function _help()
{
    cat <<EOF

This script sets the environment for using the lrstar system.

It must be loaded via 'source', like so:

  source ${SCRIPT} \\
    --bod <build-output-directory> \\

EOF
}


function process_args ()
{
    while true ; do
        case "$1" in
            -a|--architecture)
                ARCHITECTURE=$(eval echo ${2});
                case "${ARCHITECTURE}" in
                    Intel-x86-64 | Arm64)
                        # Architecture is ok.
                        ;;

                    *)
                        echo "Invalid architecture '${ARCHITECTURE}'.";
                        return 1;
                        ;;
                esac;
                shift 2;
                ;;

            -b|--build-type)
                BUILD=$(eval echo ${2});
                case "${BUILD}" in
                    debug|release)
                        # Build type is ok.
                        ;;

                    *)
                        echo "Invalid build type '${BUILD}'.";
                        return 1;
                        ;;
                esac;
                shift 2;
                ;;

            -o|--bod)
                BOD=$(eval echo ${2});
                shift 2;
                ;;


            --)                 # End of arguments
                shift;
                break;
                ;;

            *)
                echo "Unknown option '${1}'";
                return 1;
                ;;
        esac
    done

    return 0;
}


function main()
{
    ARCHITECTURE="Intel-x86-64";
    BUILD="debug";
    BOD="";

    export LRSTAR_DIR=$(readlink -f $(dirname ${BASH_SOURCE})/..);

    case ${PATH} in
        *${LRSTAR_DIR}*)
            # PATH has already been updated.  Do nothing.
            ;;
        *)
            export PATH=${LRSTAR_DIR}/scripts:$PATH;
            ;;
    esac;

    if process_args ${@} ; then
        if [ -z "${BOD}" ] ; then
            _help;
        else
            export LRSTAR_BUILD_DIR="${BOD}";
            export LRSTAR_BUILD_OPTIONS="";

            build-set-type "${BUILD}";
            lrstar-show-config;
        fi;
    else
        _help;
        echo "Local work environment configuration failed."
    fi;
}

args=$(/usr/bin/getopt -o a:b:o: --longoptions architecture:,bod:,build-type: -- "${@}")
set -- "${args}"            # Set postional args to ${args}.
unset args;

main ${@};
