// Generated by LRSTAR 24.0.017
// DO NOT EDIT.

#if !defined(__Python_Parser_H)
#define __Python_Parser_H

#include "lrstar_basic_defs.h"
#include "lrstar_lexer.h"

#include "Python_ParserTables_typedef.h"
#include "lrstar_parser.h"

extern const char Python_grammar_name[];

typedef lrstar_parser</* grammar           */   Python_grammar_name,
                      /* actions           */   false,
                      /* debug_parser      */   false,
                      /* debug_trace       */   false,
                      /* expecting         */   true,
                      /* insensitive       */   false,
                      /* lookaheads        */   3,
                      /* make_ast          */   false,
                      /* nd_parsing        */   true,
                      /* nd_threads        */   2,
                      /* node_actions      */   false,
                      /* reversable        */   false,
                      /* semantics         */   false,
                      /* stksize           */   100,
                      /* term_actions      */   false,
                      /* lexer table type  */   Python_lexer_t,
                      /* parser table type */   Python_parser_tables_t> Python_parser_t;

#endif
