
////////////////////////////////////////////////////////////////////////////////
//
//    XPL_ParserTables.h (generated by LRSTAR 24.0.017)

      #pragma once

      #include "lrstar_library_defs.h"


class lrstar_parser;

      class lrstar_parser_tables
      {
         friend class lrstar_parser;
         public:
         static const char *term_symb[    49]; // Terminal symbols of the grammar.
         static const char *head_symb[    49]; // Nonterminal symbols of the grammar.
         static const char *tact_name[     2]; // Terminal action names found in the grammar.
         static const uint8  head_numb[   109]; // Head symbol number for a production.
         static const uint8  f_tail   [   110]; // First tail in a production.
         static const int8   tail     [   221]; // Tail symbol number.
         static const int8   arga     [    49]; // Arguments for terminal actions.

         private:
         static const uint8  Bm[   118]       ; // Boolean matrix.
         static const uint8  Br[    97]       ; // Boolean matrix row.
         static const uint8  Bc[    49]       ; // Boolean matrix column.
         static const uint8 Bf[    49]       ; // Boolean matrix filter/mask.
         static const int8   Tm[   144]       ; // Terminal transition matrix.
         static const uint8  Tr[    97]       ; // Terminal transition matrix row.
         static const uint8  Tc[    49]       ; // Terminal transition matrix column.
         static const int8   Nm[   580]       ; // Nonterminal transition matrix.
         static const uint16 Nr[    97]       ; // Nonterminal transition matrix row.
         static const uint8  Nc[   109]       ; // Nonterminal transition matrix column.
         static const uint8  Rm[     1]       ; // Reduction matrix.
         static const uint8  Rr[    97]       ; // Reduction matrix row.
         static const uint8  Rc[    49]       ; // Reduction matrix column.
         static const uint8  PL[   109]       ; // Production length minus one.

         static const int8   tact_numb[    49]; // Terminal action numbers.
      };

//
////////////////////////////////////////////////////////////////////////////////

