/* This file is generated by lrstar and will be overwritten by it. */

#include "lrstar_basic_defs.h"
#include "COBOL_LexerTables_typedef.h"
#include "COBOL_Parser.h"
#include "COBOL_user.h"
#include "COBOL_user_init_actions.h"
#include "COBOL_user_term_actions.h"
#include "COBOL_user_error.h"
#include "COBOL_user_lookup.h"
