// Generated by LRSTAR 24.0.017
// DO NOT EDIT.

#if !defined(__COBOL_Parser_H)
#define __COBOL_Parser_H

#include "lrstar_basic_defs.h"
#include "lrstar_lexer.h"

#include "COBOL_ParserTables_typedef.h"
#include "lrstar_parser.h"

#endif
