
////////////////////////////////////////////////////////////////////////////////
//
//    verilog_LexerTables.h (generated by DFA 24.0.016)

      #pragma once

      #undef  DEBUG_LEXER


/*
      static const ushort Tm[ 27877]        ; // Terminal transition matrix.
      static const ushort Tr[   500]        ; // Terminal transition matrix row.
      static const uchar  Tc[   256]        ; // Terminal transition matrix column.
      static const uchar  term_numb[   500] ; // Terminal number.
*/

//
////////////////////////////////////////////////////////////////////////////////
