// Generated by LRSTAR 24.0.017
// DO NOT EDIT.

#if !defined(__Zeus_Parser_H)
#define __Zeus_Parser_H

#include "lrstar_basic_defs.h"
#include "lrstar_lexer.h"
      #undef  GRAMMAR
      #undef  ACTIONS
      #undef  TERM_ACTIONS
      #undef  NODE_ACTIONS
      #undef  INSENSITIVE
      #undef  LOOKAHEADS
      #undef  DEBUG_PARSER
      #undef  DEBUG_TRACE
      #undef  MAKE_AST
      #undef  EXPECTING
      #undef  REVERSABLE
      #undef  SEMANTICS
      #undef  ND_PARSING
      #undef  ND_THREADS

      #define GRAMMAR      "Zeus"
      #define ACTIONS       Zeus_Actions
      #define TERM_ACTIONS  Zeus_TermActions
      #define LOOKAHEADS    1
      #define EXPECTING

#include "Zeus_ParserTables_typedef.h"
#include "lrstar_parser.h"

#endif
