
////////////////////////////////////////////////////////////////////////////////
//
//    Zeus_ParserTables.h (generated by LRSTAR 24.0.017)

      #pragma once

      #undef  GRAMMAR
      #undef  PARSER
      #undef  PARSER_TABLES
      #undef  LEXER
      #undef  ACTIONS
      #undef  TERM_ACTIONS
      #undef  NODE_ACTIONS
      #undef  INSENSITIVE
      #undef  LOOKAHEADS
      #undef  DEBUG_PARSER
      #undef  DEBUG_TRACE
      #undef  MAKE_AST
      #undef  EXPECTING
      #undef  REVERSABLE
      #undef  SEMANTICS
      #undef  ND_PARSING
      #undef  ND_THREADS

      #define GRAMMAR      "Zeus"
      #define PARSER        Zeus_Parser
      #define PARSER_TABLES Zeus_ParserTables
      #define LEXER         Zeus_Lexer
      #define ACTIONS       Zeus_Actions
      #define TERM_ACTIONS  Zeus_TermActions
      #define LOOKAHEADS    1
      #define EXPECTING


      #define TOP_DOWN  0
      #define PASS_OVER 1
      #define BOTTOM_UP 2

      class Zeus_ParserTables
      {
         friend class Zeus_Parser;
         public:
         static const char *term_symb[    71]; // Terminal symbols of the grammar.
         static const char *head_symb[   114]; // Nonterminal symbols of the grammar.
         static const char *tact_name[     2]; // Terminal action names found in the grammar.
         static const uchar  head_numb[   222]; // Head symbol number for a production.
         static const ushort f_tail   [   223]; // First tail in a production.
         static const char   tail     [   479]; // Tail symbol number.
         static const char   arga     [    71]; // Arguments for terminal actions.

         private:
         static const uchar  Bm[   340]       ; // Boolean matrix.
         static const ushort Br[   229]       ; // Boolean matrix row.
         static const uchar  Bc[    71]       ; // Boolean matrix column.
         static const uchar Bf[    71]       ; // Boolean matrix filter/mask.
         static const short  Tm[   400]       ; // Terminal transition matrix.
         static const ushort Tr[   229]       ; // Terminal transition matrix row.
         static const uchar  Tc[    71]       ; // Terminal transition matrix column.
         static const short  Nm[  1154]       ; // Nonterminal transition matrix.
         static const ushort Nr[   229]       ; // Nonterminal transition matrix row.
         static const uchar  Nc[   222]       ; // Nonterminal transition matrix column.
         static const uchar  Rm[     1]       ; // Reduction matrix.
         static const uchar  Rr[   229]       ; // Reduction matrix row.
         static const uchar  Rc[    71]       ; // Reduction matrix column.
         static const char   PL[   222]       ; // Production length minus one.

         static const char   tact_numb[    71]; // Terminal action numbers.

         static void   (*init_func[    2]) ()       ; // Init action function pointers.
         static int    (*tact_func[    2]) (int& t) ; // Terminal action function pointers.
      };

//
////////////////////////////////////////////////////////////////////////////////

