
//
//    NCSA_ParserTables.h (generated by LRSTAR 24.0.017)

#pragma once

#include "lrstar_library_defs.h"

enum nodecon {
   N_Report = 0,
   N_Day = 1,
   N_Client = 2,
   N_FullName = 3,
   N_Name = 4,
   N_Time = 5,
   N_File = 6,
   N_Code = 7,
   N_Size = 8,
   N_Source = 9,
   N_Query = 10,
};

