
////////////////////////////////////////////////////////////////////////////////
//
//    Java1_LexerTables.h (generated by DFA 24.0.016)

      #pragma once

      #undef  DEBUG_LEXER


/*
      static const ushort Tm_[ 26280]        ; // Terminal transition matrix.
      static const ushort Tr_[   393]        ; // Terminal transition matrix row.
      static const uchar  Tc_[   256]        ; // Terminal transition matrix column.
      static const char   term_numb_[   393] ; // Terminal number.
*/

//
////////////////////////////////////////////////////////////////////////////////
