
////////////////////////////////////////////////////////////////////////////////
//
//    Java1_ParserTables.h (generated by LRSTAR 24.0.017)

      #pragma once

      #undef  GRAMMAR
      #undef  PARSER
      #undef  PARSER_TABLES
      #undef  LEXER
      #undef  ACTIONS
      #undef  TERM_ACTIONS
      #undef  NODE_ACTIONS
      #undef  INSENSITIVE
      #undef  LOOKAHEADS
      #undef  DEBUG_PARSER
      #undef  DEBUG_TRACE
      #undef  MAKE_AST
      #undef  EXPECTING
      #undef  REVERSABLE
      #undef  SEMANTICS
      #undef  ND_PARSING
      #undef  ND_THREADS

      #define GRAMMAR      "Java1"
      #define PARSER        Java1_Parser
      #define PARSER_TABLES Java1_ParserTables
      #define LEXER         Java1_Lexer
      #define ACTIONS       Java1_Actions
      #define TERM_ACTIONS  Java1_TermActions
      #define LOOKAHEADS    1
      #define EXPECTING

      enum termcon
      {
         BOOLEAN = 4,
         CHAR = 5,
         BYTE = 6,
         SHORT = 7,
         INT = 8,
         LONG = 9,
         FLOAT = 10,
         DOUBLE = 11,
         VOID = 12,
         ENUM = 13,
         PACKAGE = 14,
         IMPORT = 15,
         ABSTRACT = 16,
         FINAL = 17,
         PUBLIC = 18,
         PROTECTED = 19,
         PRIVATE = 20,
         STATIC = 21,
         TRANSIENT = 22,
         VOLATILE = 23,
         NATIVE = 24,
         SYNCHRONIZED = 25,
         CLASS = 26,
         INTERFACE = 27,
         IMPLEMENTS = 28,
         OP_DIM = 29,
         THROWS = 30,
         EXTENDS = 31,
         CASE = 32,
         DEFAULT = 33,
         IF = 34,
         ELSE = 35,
         SWITCH = 36,
         WHILE = 37,
         DO = 38,
         FOR = 39,
         BREAK = 40,
         CONTINUE = 41,
         RETURN = 42,
         THROW = 43,
         TRY = 44,
         CATCH = 45,
         FINALLY = 46,
         THIS = 47,
         SUPER = 48,
         JNULL = 49,
         NEW = 50,
         INSTANCEOF = 51
      };


      #define TOP_DOWN  0
      #define PASS_OVER 1
      #define BOTTOM_UP 2

      class Java1_ParserTables
      {
         friend class Java1_Parser;
         public:
         static const char *term_symb[    99]; // Terminal symbols of the grammar.
         static const char *head_symb[    99]; // Nonterminal symbols of the grammar.
         static const char *tact_name[     2]; // Terminal action names found in the grammar.
         static uchar  head_numb[   270]; // Head symbol number for a production.
         static ushort f_tail   [   271]; // First tail in a production.
         static char   tail     [   568]; // Tail symbol number.
         static char   arga     [    99]; // Arguments for terminal actions.

         private:
         static uchar  Bm[   266]       ; // Boolean matrix.
         static ushort Br[   236]       ; // Boolean matrix row.
         static uchar  Bc[    99]       ; // Boolean matrix column.
         static uchar  Bf[    99]       ; // Boolean matrix filter/mask.
         static short  Tm[   608]       ; // Terminal transition matrix.
         static ushort Tr[   236]       ; // Terminal transition matrix row.
         static uchar  Tc[    99]       ; // Terminal transition matrix column.
         static short  Nm[  3135]       ; // Nonterminal transition matrix.
         static ushort Nr[   236]       ; // Nonterminal transition matrix row.
         static uchar  Nc[   270]       ; // Nonterminal transition matrix column.
         static uchar  Rm[    49]       ; // Reduction matrix.
         static short  Rr[   236]       ; // Reduction matrix row.
         static uchar  Rc[    99]       ; // Reduction matrix column.
         static char   PL[   270]       ; // Production length minus one.

         static char   tact_numb[    99]; // Terminal action numbers.

         static void   (*init_func[    2]) ()       ; // Init action function pointers.
         static int    (*tact_func[    2]) (int& t) ; // Terminal action function pointers.
      };

//
////////////////////////////////////////////////////////////////////////////////

